#!/usr/local/bin/python
# ----------------------------------------------------------------------
# TM and (c) 2009 DreamWorks Animation LLC.  All Rights Reserved.
# Reproduction in whole or in part without prior written permission of a
# duly authorized representative is prohibited.
# ----------------------------------------------------------------------
"""
Application module for mongo_template_ingest
"""
__version__ = "$Id: mongo_template_ingest,v 1.15 2008/04/01 01:31:32 jono Exp $"
__source__ = "$Source: /rel/cvsroot/cmd/src_cmd/src_create/templates/python_program/mongo_template_ingest,v $"
__author__ = "Jeffrey Jose"

# Python Modules
import sys, os

# Studio Modules
import studioenv
import studio.framework.app

from studio.utils.path import Path

import mongodbutils

class App(studio.framework.app.App):
    """
    """

    def addCmdlineFlags(self, cl):
        """Adds command line flags to the application.

        :Parameters:
            cl
                Instance of an studio.utils.cmdline object.
        """
        super(App, self).addCmdlineFlags(cl)
        cl.addArg('<templates> ...',  'List of template html files to ingest', convert = Path)

        cl.addFlag('-host <host>', 'The MongoDB host to connect to', default = os.environ['HOSTNAME'])
        cl.addFlag('-port <port>', 'The MongoDB port to connect to', default = 8090, convert = int)

    def configureOptions(self, opts):
        """Configures the application options.

        :Parameters:
            opts
                Dictionary of options parsed from command line flags.
        """

        opts = super(App, self).configureOptions(opts)

        return opts


    def main(self):
        """Application entry point."""
        super(App, self).main()


        mongo = mongodbutils.MongoDB(self.opts['host'], self.opts['port'])

        connection = mongo.connection['perform']

        for templateFile in self.opts['templates']:
            contents = "".join(templateFile.readLines(retain = False))

            id = templateFile.nameBase

            # For now name of the template is the id itself
            name = id

            template = mongo.createTemplate(name, id, contents)

            print 'Adding %s (%s)' % (name, id)
            connection.templates.insert(template, safe = True)


if __name__ == '__main__':
    App().run()


# ----------------------------------------------------------------------
# TM and (c) 2009 DreamWorks Animation LLC.  All Rights Reserved.
# Reproduction in whole or in part without prior written permission of a
# duly authorized representative is prohibited.
# ----------------------------------------------------------------------
